
package main.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.0.16
 * Wed Jan 17 11:52:51 IST 2018
 * Generated source version: 3.0.16
 */

@XmlRootElement(name = "substractResponse", namespace = "http://main/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "substractResponse", namespace = "http://main/")

public class SubstractResponse {

    @XmlElement(name = "return")
    private int _return;

    public int getReturn() {
        return this._return;
    }

    public void setReturn(int new_return)  {
        this._return = new_return;
    }

}

